app:
  name: leagueManager-api
  description: League Manager Backend API

---
#Active environment
spring:
  profiles:
    active: dev

---
#Dev settings
spring:
  profiles: dev

  datasource:
    url: jdbc:mariadb://localhost:3306/league_manager_dev
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  #Logging
  #logging:
    #config: classpath:logging/dev-logback-spring.groovy

server:
  port: 8080

---
#Prod settings
spring:
  profiles: prod

  datasource:
    url: jdbc:mariadb://localhost:3306/league_manager
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080